package ai.genaifund.beyondpilot.solution.dto;

import java.util.List;
import java.util.UUID;

import io.swagger.v3.oas.annotations.media.Schema;
import org.jspecify.annotations.Nullable;

@Schema(name = "PublicSolution", description = "An approved solution as anyone with its address reads it, listed or not.")
public record PublicSolutionResponse(@Schema(requiredMode = Schema.RequiredMode.REQUIRED) String slug,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) String name,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) String organizationName,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED,
				description = "The address of the organization's public page.") String organizationSlug,
		@Schema(types = { "string", "null" }, description = "ISO 3166-1 alpha-2.") @Nullable String country,
		@Schema(types = { "integer", "null" }, description = "The year the organization started.") @Nullable Integer organizationFoundedYear,
		@Schema(types = { "string", "null" },
				description = "The organization's team-size vocabulary code, when one is known.") @Nullable String organizationTeamSize,
		@Schema(types = { "string", "null" },
				description = "Its exact imported company-size label; null for an organization that has not supplied one.") @Nullable String organizationCompanySizeLabel,
		@Schema(types = { "string", "null" }) @Nullable String summary,
		@Schema(types = { "string", "null" }) @Nullable String problemsSolved,
		@Schema(types = { "string", "null" }) @Nullable String valueProposition,
		@Schema(types = { "string", "null" },
				allowableValues = { "idea", "prototype", "pilot", "production", "scaled" }) @Nullable String maturity,
		@Schema(types = { "string", "null" }) @Nullable String traction,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED,
				description = "Product names the company listed in the v1 export.") List<String> productNames,
		@Schema(types = { "string", "null" }) @Nullable String coreTechnology,
		@Schema(types = { "string", "null" }) @Nullable String infrastructureUsed,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> segmentFocus,
		@Schema(types = { "string", "null" },
				description = "Customers named by the company; these are not reviewed customer deployments.") @Nullable String notablePayingCustomers,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> useCaseIndustries,
		@Schema(types = { "string", "null" },
				description = "Use-case descriptions stated by the company, separate from reviewed customer deployments.") @Nullable String useCaseDescriptions,
		@Schema(types = { "string", "null" }) @Nullable String monetizationModel,
		@Schema(types = { "string", "null" },
				description = "The company's stated funding status, distinct from GenAI Fund's backing.") @Nullable String companyFundingStatus,
		@Schema(types = { "string", "null" },
				description = "The amount the company stated it raised, including its original wording and currency.") @Nullable String companyFundingRaised,
		@Schema(types = { "string", "null" }) @Nullable String competitors,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> builtWith,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> industries,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> focusAreas,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> languages,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<String> deployment,
		@Schema(types = { "string", "null" }) @Nullable String channels,
		@Schema(types = { "string", "null" }) @Nullable String bestCustomerProfile,
		@Schema(types = { "object", "null" },
				description = "What GenAI Fund says of it; null when it has said nothing.") @Nullable SolutionBackingResponse backing,
		@Schema(types = { "string", "null" }) @Nullable String website,
		@Schema(types = { "string", "null" }) @Nullable String demoUrl,
		@Schema(types = { "object", "null" }, description = "Its deck, when it has one.") @Nullable PublicSolutionDeckResponse deck,
		@Schema(types = { "string", "null" }, format = "uuid",
				description = "Its logo, or its organization's when it has none, read at /api/storage/files/{id}; null when neither has one.") @Nullable UUID logoFileId,
		@Schema(types = { "string", "null" }, format = "uuid",
				description = "Its cover, read at /api/storage/files/{id}; null for none.") @Nullable UUID coverFileId,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED,
				description = "The images shown under the cover, in their order, each read at "
						+ "/api/storage/files/{id}.") List<UUID> imageFileIds,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED,
				description = "Whether the directory lists it. False is approved but shared by its address only.") boolean listed,
		@Schema(requiredMode = Schema.RequiredMode.REQUIRED,
				description = "Its approved customer deployments, the most recently approved first.") List<PublicCustomerDeploymentResponse> customerDeployments) {
}
