"""Turn the saved website text of the imported solutions into SQL for the passages search keeps (BEY-39).

    python -I passages.py <enrich folder> <out folder>

reads <enrich folder>/input.json (each solution's id and name) and <enrich folder>/sources/<id>.web-N.txt (the first
line is the page's address), and writes
- passages.sql: every website passage in one transaction. A second load puts the same rows in the place of the first;
- passages.json: the counts.
A line that every page of one website repeats (its menu, its footer) is left out. A page is cut into passages the way
the application cuts one (`search.Passages`: at line ends, 2,000 characters a passage, 20,000 a page). Decks are not
loaded here: the application extracts them from the stored files, so imported and new decks are read the same way.
"""

import collections
import json
import re
import sys
import urllib.parse
from pathlib import Path

PASSAGE_CHARACTERS = 2000
PAGE_CHARACTERS = 20_000
ORIGIN = "legacy-import"
ROWS_PER_INSERT = 200
WEB_FILE = re.compile(r"^(?P<id>[0-9a-f-]{36})\.web-(?P<number>\d+)\.txt$")


def lit(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("\x00", "").replace("'", "''") + "'"


def cut(page: str) -> list[str]:
    """The passages of a page, as search.Passages.cut makes them."""
    text = page.replace("\r\n", "\n").replace("\r", "\n").strip()[:PAGE_CHARACTERS]
    passages, current = [], ""
    for line in text.split("\n"):
        rest = line.rstrip()
        while len(rest) > PASSAGE_CHARACTERS:
            if current.strip():
                passages.append(current.strip())
            current = ""
            space = rest.rfind(" ", 0, PASSAGE_CHARACTERS + 1)
            end = space if space > PASSAGE_CHARACTERS // 2 else PASSAGE_CHARACTERS
            passages.append(rest[:end].strip())
            rest = rest[end:].strip()
        if len(current) + len(rest) + 1 > PASSAGE_CHARACTERS:
            if current.strip():
                passages.append(current.strip())
            current = ""
        if rest.strip() or current:
            current += rest + "\n"
    if current.strip():
        passages.append(current.strip())
    return passages


def heading(name: str, address: str) -> str:
    parts = urllib.parse.urlsplit(address)
    place = (parts.hostname or "") + (parts.path if parts.path not in ("", "/") else "")
    return f"{name}, {place}"[:200]


def main() -> None:
    work, out = Path(sys.argv[1]), Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)
    names = {record["id"]: record["name"] for record in json.loads((work / "input.json").read_text(encoding="utf-8"))}
    sites = collections.defaultdict(dict)
    for path in sorted((work / "sources").iterdir()):
        match = WEB_FILE.match(path.name)
        if match and match["id"] in names:
            sites[match["id"]][int(match["number"])] = path.read_text(encoding="utf-8", errors="replace")

    rows, counts = [], collections.Counter()
    for solution_id, pages in sorted(sites.items()):
        addresses, lines = {}, {}
        for number, text in pages.items():
            address, _, body = text.partition("\n")
            addresses[number] = address.strip()
            lines[number] = [line.strip() for line in body.split("\n") if line.strip()]
        repeated = set()
        if len(lines) >= 2:
            seen = collections.Counter(line for page in lines.values() for line in set(page))
            repeated = {line for line, times in seen.items() if times == len(lines)}
        wrote = False
        for place, number in enumerate(sorted(lines), start=1):
            kept = [line for line in lines[number] if line not in repeated]
            counts["characters_before"] += sum(len(line) + 1 for line in lines[number])
            counts["characters_after"] += sum(len(line) + 1 for line in kept)
            page = "\n".join(kept)
            counts["pages_cut_at_the_limit"] += len(page) > PAGE_CHARACTERS
            for part, passage in enumerate(cut(page)):
                rows.append((solution_id, place, part, addresses[number], heading(names[solution_id], addresses[number]),
                             passage))
                wrote = True
            counts["pages"] += bool(kept)
        counts["solutions"] += wrote
    counts["passages"] = len(rows)

    sql = ["-- Website passages of the imported solutions (BEY-39). Generated by passages.py; not committed.",
           "begin;",
           f"delete from search_passage where source = 'website' and origin = '{ORIGIN}';"]
    for start in range(0, len(rows), ROWS_PER_INSERT):
        values = ",\n".join(
            f"  ({lit(solution_id)}::uuid, {place}, {part}, {lit(address)}, {lit(head)}, {lit(text)})"
            for solution_id, place, part, address, head, text in rows[start:start + ROWS_PER_INSERT])
        sql.append(
            "insert into search_passage (solution_id, source, page, part, locator, heading, text, reading, origin)\n"
            f"select v.solution_id, 'website', v.page, v.part, v.locator, v.heading, v.text, 'text', '{ORIGIN}'\n"
            f"from (values\n{values}\n) as v(solution_id, page, part, locator, heading, text)\n"
            "where exists (select 1 from solution s where s.id = v.solution_id);")
    sql.append("do $$ begin raise notice '% website passages of % solutions are kept', "
               f"(select count(*) from search_passage where origin = '{ORIGIN}'), "
               f"(select count(distinct solution_id) from search_passage where origin = '{ORIGIN}'); end $$;")
    sql.append("commit;")
    (out / "passages.sql").write_text("\n".join(sql) + "\n", encoding="utf-8", newline="\n")
    (out / "passages.json").write_text(json.dumps(dict(counts), indent=1) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps(dict(counts)))


if __name__ == "__main__":
    main()
